name: ReDoc for OpenAPI UI
type: module
description: Provides display of OpenAPI docs using the ReDoc library.
core: 8.x
core_version_requirement: '^8 || ^9'
package: OpenAPI
dependencies:
  - openapi_ui:openapi_ui

# Information added by Drupal.org packaging script on 2020-08-26
version: '8.x-1.0-rc3'
project: 'openapi_ui_redoc'
datestamp: 1598462001
