<?php

/**
 * @file
 * Contains locator_view.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function locator_view_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the th_store_locator_view module.
    case 'help.page.locator_view':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Store Locator View module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function locator_view_preprocess_views_view(&$variables) {
  // add form before the view,
  // this is a alternative to print the form in DefaultController, keep only one variant
  // $form = \Drupal::formBuilder()->getForm('\Drupal\locator_view\Form\OriginLocationForm');
  // $variables['attachment_before'][] = $form;
}
