<?php

/**
 * Implements hook_page_attachments_alter().
 */
function react_thm_page_attachments_alter(array &$attachments) {
  // Use the dev library if we're developing locally.
  if (in_array('react_thm/react_app', $attachments['#attached']['library']) && file_exists(__DIR__ . '/js/dist_dev')) {
    $index = array_search('react_thm/react_app', $attachments['#attached']['library']);
    $attachments['#attached']['library'][$index] = 'react_thm/react_app_dev';
  }
}