layout_builder_component_attributes.settings:
  type: config_object
  label: 'Layout Builder Component Attributes'
  mapping:
    allowed_block_attributes:
      type: mapping
      label: 'Allowed Block Attributes'
      mapping:
        id:
          type: boolean
          label: 'ID'
        class:
          type: boolean
          label: 'Class(es)'
        style:
          type: boolean
          label: 'Inline CSS styles'
        data:
          type: boolean
          label: 'Data-* attributes'
    allowed_block_title_attributes:
      type: mapping
      label: 'Allowed Block Title Attributes'
      mapping:
        id:
          type: boolean
          label: 'ID'
        class:
          type: boolean
          label: 'Class(es)'
        style:
          type: boolean
          label: 'Inline CSS styles'
        data:
          type: boolean
          label: 'Data-* attributes'
    allowed_block_content_attributes:
      type: mapping
      label: 'Allowed Block Content Attributes'
      mapping:
        id:
          type: boolean
          label: 'ID'
        class:
          type: boolean
          label: 'Class(es)'
        style:
          type: boolean
          label: 'Inline CSS styles'
        data:
          type: boolean
          label: 'Data-* attributes'
