geolocation.map_provider.leaflet:
  type: geolocation_map_provider
  label: 'Leaflet settings'
  mapping:
    zoom:
      type: string
      label: 'Zoom level'
    height:
      type: string
      label: 'Height value'
    width:
      type: string
      label: 'Width value'

geolocation.geocoder.photon:
  type: geolocation_geocoder
  label: 'Photon geocoder'
  mapping:
    autocomplete_min_length:
      type: integer
      label: 'Autocomplete MinLength'
    location_priority:
      type: geolocation.element.input
      label: 'Location Priority'
    remove_duplicates:
      type: boolean
      label: 'Remove Duplicates'

geolocation_leaflet.nominatim_settings:
  type: config_object
  label: 'Nominatim geocoding settings'
  mapping:
    nominatim_base_url:
      type: string
      label: 'Nominatim Base URL Override'
    nominatim_email:
      type: email
      label: 'Custom Email for Nominatim Requests'
